### PR TITLE
feat: add unreleased splunk

### PR DESCRIPTION
**Pull request by mkolasinski-splunk**
Add unreleased splunk with python 3.9 to splunk_matrix for test purposes.

### CODE REVIEW

**Review by mbruzda-splunk — APPROVED** [review]

**Comment by artemrys** [comment]
Can we store instructions somewhere on how to achieve the same in the future?

**Comment by mkolasinski-splunk** [comment]
@artemrys we can either create confluence page to keep track on progress of python 3.9 migration in TAs. I could add some notes to this repo readme how to add unreleased splunk for testing

**Comment by artemrys** [comment]
Let's have it in confluence.

**Review by artemrys — APPROVED** [review]

**Pull request merged**
